### ISSUE TITLE
Mechanic fails with "Cannot find restored info for project..."

### ISSUE THREAD

**Issue by tforkmann** [ionide/ionide-vscode-mechanic#21]
Error message:

![image](https://user-images.githubusercontent.com/4168951/37455577-af567026-283d-11e8-9875-40f7b979567d.png)

Any ideas how to fix that?

**Comment by jindraivanek** [comment]
This is most probably because `dotnet restore` fails. You can try to do restore on project and run again. @tforkmann it is possible to upload this project for repro?

Maybe Mechanic should only emit warning when something goes wrong with ProjectCracker and continue without considering external defs.

**Comment by tforkmann** [comment]
Ok that helped! 

Could Mechanic maybe run `dotnet restore` for me?

**Comment by jindraivanek** [comment]
Mechanic do it, but it fails here for some reason.

**Comment by tforkmann** [comment]
Ok closing it now
